[build]
  command = "npm run build"
  functions = "functions"
  publish = "build"

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200

[[redirects]]
  from = '/api/gas/trend'
  to = '/.netlify/functions/trend'

[[redirects]]
  from = '/api/alerts/stats'
  to = '/.netlify/functions/alerts'
  status = 200

[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200